version: "3"
services:
  node:
    image: node:10.16.3-alpine
    working_dir: "/app"
    environment:
      - SLACK_TOKEN
      - CONOHA_PASS
      - CONOHA_TENANT_ID
      - CONOHA_USERNAME
    volumes:
      - ./:/app